config/routes.rb
Whois::Application.routes.draw do
  resources :queries, only: [:new, :create]
  match '/queries', to: 'queries#new'
  root :to => 'queries#new'
end

app/models/query.rb
class Query
  attr_reader :query

  delegate :content, :server, :available?, to: :result
  delegate :host, to: :server

  def initialize(query)
    @query = query
  end

  def result
    @result ||= Whois::Client.new.query(@query)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  def new
  end

  def create
    @query = QueryDecorator.decorate(Query.new(params[:query]))
    render 'new'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Whois
    %link{:href => "http://fonts.googleapis.com/css?family=Open+Sans", :rel => "stylesheet", :type => "text/css"}
      = stylesheet_link_tag    "application", :media => "all"
      = javascript_include_tag "application"
      = csrf_meta_tags
  %body
    = yield

app/views/queries/new.html.haml
= form_tag queries_path, id: 'queryForm', class: 'query-form clearfix' do
  = button_tag 'Submit', type: :submit, class: 'search_action'
  = text_field_tag :query, '', autocorrect: 'off',  autocomplete: 'off', spellcheck: false, placeholder: 'Enter Domain'

- if @query
  .whois-result
    %table
      %tr
        %td Query:
        %td= @query.query
      %tr
        %td Host:
        %td= @query.host
      %tr
        %td Available:
        %td= @query.available?
    %hr
    %p= @query.content.html_safe